# Generated by Django 5.0.4 on 2024-05-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='iamge',
            new_name='image',
        ),
    ]
